version 1.0.1

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,4 +1,10 @@
-LIBFILE=$(whereis libapparmor.so | grep -oh " [a-zA-Z0-9/]*libapparmor.so")
+if [ ! -e /usr/include/sys/apparmor.h ]
+then
+  echo "sys/apparmor.h not found. Make sure libapparmor-dev is installed."
+  exit 1
+fi
+
+LIBFILE=$(/sbin/ldconfig -p | egrep -oh " [-_a-zA-Z0-9/]*/libapparmor.so(.1)?$")
 
 if [ -z "$LIBFILE" ]
 then
